#ifndef SYSTICK_CONF_H
#define SYSTICK_CONF_H

#define SYSTICK_CLOCK_SOURCE			SYSTICK_CLOCK_SOURCE_PROCESSOR_DIV8
#define SYSTICK_CLOCK_FREQ_KHZ			2000UL		// 16 MHz / 8 = 2 MHz = 2000 KHz
#define SYSTICK_MAX_TICKS               0xFFFFFFUL

#endif //SYSTICK_CONF_H